# Dockerfile
# To run this container :
# docker run --rm  -v some_local_storage_folder:/etc/wingbits/device --device=/dev/ttyACM0:/dev/ttyACM0 -p 30006:30006 vapolia/wingbits:latest-amd64
#
# TODO: check ownership of tty (dialout or tty): 
# ls -l /dev/ttyACM0
# sudo usermod -aG dialout $USER
#
# Test device access:
# docker run --rm --device=/dev/ttyACM0:/dev/ttyACM0 debian:bookworm-slim cat /dev/ttyACM0
#
# Test presence of geosigner
# wingbits status
# wingbits feeder status
# the connected message will change when you have a geosigner installed, it will be "over TLS/TCP" instead of "over TCP"



# python is required by the wingbits binary, for initial onboarding of the geosigner.
FROM python:3-slim-bookworm

#Automatic args
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

RUN echo "Building for platform: $TARGETPLATFORM ($TARGETOS-$TARGETARCH)"

# Install necessary utilities
RUN apt-get update && apt-get install -y \
    curl \
    gzip \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/wingbits

# Fetch and store the version information
RUN VERSION_URL="https://install.wingbits.com/$TARGETOS-$TARGETARCH.json" && \
    curl -s "$VERSION_URL" | grep -o '"Version": "[^"]*"' | cut -d'"' -f4 > /etc/wingbits/version

# Fetch and install the Wingbits executable
RUN VERSION=$(cat /etc/wingbits/version) && \
    EXECUTABLE_URL="https://install.wingbits.com/$VERSION/$TARGETOS-$TARGETARCH.gz" && \
    curl -s "$EXECUTABLE_URL" -o /usr/local/bin/wingbits.gz && \
    gunzip /usr/local/bin/wingbits.gz && \
    chmod +x /usr/local/bin/wingbits && \
    rm -f /usr/local/bin/wingbits.gz

# Create necessary configuration files
RUN echo "" > /etc/wingbits/device

# Expose ports
EXPOSE 30006 30015

# Set the executable as the default command
CMD ["/usr/local/bin/wingbits", "feeder", "start"]
